dataset:
  name: grab
  root: data/grab
  obj_root: data/grab/processed_object_meshes
  data_path: data/grab/data.npz
  data_obj_pc_path: data/grab/obj.pkl
  balance_weights_path: data/grab/balance_weights.pkl
  text_json: data/grab/text.json
  t2l_json: data/grab/text_length.json
  t2c_json: data/grab/text_count.json
  flat_hand: true
  max_nframes: 150
  data_ratio: 1
  augm: false
  data_num: 1335
  text_num: 276
clip:
  clip_version: ViT-B/32
diffusion:
  beta_1: 0.0001
  beta_T: 0.02
  T: 1000
  schedule_name: cosine
mpnet:
  version: sentence-transformers/all-mpnet-base-v2
seq_cvae:
  model_name: seq_cvae
  latent_dim: 64
  cond_dim: 512
  encoder_layer_dims:
  - 1
  - 512
  decoder_layer_dims:
  - 512
  - 1
  final_sigmoid: true
  iteration: 1000
  lr: 0.001
  save_root: outputs/${seq_cvae.model_name}
  weight_path: checkpoints/${dataset.name}/${seq_cvae.model_name}.pth
pointfeat:
  model_name: pointfeat
  global_feat: false
  feature_transform: false
  in_dim: 3
  resume: false
  save_root: outputs/${pointfeat.model_name}
  weight_path: checkpoints/${dataset.name}/${pointfeat.model_name}.pth
contact:
  model_name: contact_estimator
  latent_dim: 64
  cond_dim: 1601
  use_scale: true
  use_dice_loss: true
  decoder_layer_dims:
  - 512
  - 256
  - 128
  - 1
  final_sigmoid: true
  in_dim: 4
  test_iteration: 1
  iteration: 10000
  lr: 0.001
  save_root: data/networks/contact_estimator/${dataset.name}
  weight_path: checkpoints/${dataset.name}/${contact.model_name}.pth
texthom:
  model_name: texthom
  hand_nfeats: 99
  obj_nfeats: 9
  latent_dim: 512
  ff_size: 1024
  num_layers: 8
  num_heads: 4
  dropout: 0.1
  activation: gelu
  clip_dim: 512
  obj_dim: 1024
  cond_mask_prob: 0.1
  use_cond_fc: true
  use_obj_scale_centroid: true
  use_frame_pos: true
  use_contact_feat: true
  use_inst_pos: true
  iteration: 30000
  lr: 0.0001
  lambda_simple: 1.0
  lambda_dist: 1.0
  lambda_ro: 1.0
  save_root: outputs/${texthom.model_name}
  weight_path: checkpoints/${dataset.name}/${texthom.model_name}.pth
refiner:
  model_name: refiner
  hand_input_nfeats: 2273
  hand_output_nfeats: 99
  latent_dim: 512
  ff_size: 1024
  num_layers: 8
  num_heads: 4
  dropout: 0.1
  activation: gelu
  clip_dim: 512
  obj_dim: 1024
  cond_mask_prob: 0.1
  use_cond_fc: true
  use_obj_scale_centroid: true
  zero_initialized: true
  global_feat: true
  feature_transform: false
  in_dim: 4
  iteration: 3000
  lr: 0.0001
  contact_loss_type: l1
  lambda_simple: 1.0
  lambda_penet: 1.0
  lambda_contact: 5.0
  save_root: outputs/${refiner.model_name}
  weight_path: checkpoints/${dataset.name}/${refiner.model_name}.pth
project_name: texthom
batch_size: 64
shuffle: true
drop_last: true
num_workers: 4
result_show_freq: 50
save_pth_freq: 200
text:
- Place cappuccino with right hand.
save_demo: false
save_obj: false
balance_weights: true
fps: 30
